name: "BUILD DEBUDA"

on:
  workflow_call:
    inputs:
      arch:
        required: false
        type: string
        # Add grayskull when we switch to remote
        default: '["wormhole_b0"]'
      os:
        required: false
        type: string
        default: "ubuntu-22.04"
      config:
        required: false
        type: string
        default: "ci"

run-name: Build DEBUDA by @${{ github.actor }} triggered by ${{ github.event_name }} event (${{ github.ref_name }})

jobs:
  build_libs:
    strategy:
      matrix:
        arch: ${{ fromJson(inputs.arch || '["grayskull", "wormhole_b0", "blackhole"]') }}
    env:
      ARCH_NAME: ${{ matrix.arch }}
      CONFIG: ${{ inputs.config }}
      # So we can get all the makefile output we want
      VERBOSE: 1
    # TODO: This will need to change when we get cloud runners
    runs-on: "ubuntu-22.04"
    name: "Build DEBUDA for ${{ matrix.arch }}"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: ./.github/actions/install-dbd-deps
        with:
          os: ${{ inputs.os }}
      - name: Build DEBUDA
        run: |
          make -j$(nproc) ARCH_NAME=$ARCH_NAME CONFIG=$CONFIG build
      - name: Remove unnecessary artifacts
        # TODO: Is this unneccessary?
        run: |
          find build/ -name *.so -or -name *.a -or -name *.o | xargs strip -d
      - name: 'Tar files'
        run: tar -cvf dbd_${{ matrix.arch }}.tar build
      - name: Upload libraries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbd-build-${{ matrix.arch }}
          path: dbd_${{ matrix.arch }}.tar